sonar.projectKey=ordexxa_ordexxa-backend
sonar.organization=ordexxa
sonar.projectName=Ordexxa Backend
sonar.projectVersion=0.0.1-SNAPSHOT

sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes

sonar.sourceEncoding=UTF-8
