sonar.projectKey=ordexxa_ordexxa-backend
sonar.organization=ordexxa
sonar.projectName=Ordexxa Backend
sonar.projectVersion=0.0.2-sonar

sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes

sonar.sourceEncoding=UTF-8

# Integraciones externas/configuracion sin pruebas unitarias en esta fase MVP.
sonar.coverage.exclusions=src/main/java/co/edu/uco/ordexxa/features/ops/**,src/main/java/co/edu/uco/ordexxa/infrastructure/config/**,src/main/java/co/edu/uco/ordexxa/OrdexxaBackendApplication.java
